FROM nvidia/cuda:10.0-cudnn7-devel AS compile-image

#get deps
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
python3.7-dev python3-pip git g++ wget make libprotobuf-dev protobuf-compiler libopencv-dev \
libgoogle-glog-dev libboost-all-dev libcaffe-cuda-dev libhdf5-dev libatlas-base-dev

#replace cmake as old version has CUDA variable bugs
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz && \
tar xzf cmake-3.16.0-Linux-x86_64.tar.gz -C /opt && \
rm cmake-3.16.0-Linux-x86_64.tar.gz
ENV PATH="/opt/cmake-3.16.0-Linux-x86_64/bin:${PATH}"

#get openpose
WORKDIR /openpose
RUN git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git .

#build it
WORKDIR /openpose/build
#patch because dataset server posefs1.perception.cs.cmu.edu is unavailable (2020-05-15)
RUN sed 's/posefs1.perception.cs.cmu.edu/opencv.facetraining.mobiledgex.net/g' /openpose/models/getModels.sh
RUN cmake -DBUILD_PYTHON=ON .. && make -j `nproc`

# Use a virtualenv for all of our Python requirements.
RUN apt-get install -y python3.7-venv
# Giant list of dependencies for imagecodecs package. See https://pypi.org/project/imagecodecs/
RUN apt-get install -y python3-blosc python3-brotli python3-snappy python3-lz4 libz-dev libblosc-dev \
liblzma-dev liblz4-dev libzstd-dev libpng-dev libwebp-dev libbz2-dev libopenjp2-7-dev libjpeg-turbo8-dev \
libjxr-dev liblcms2-dev libcharls-dev libaec-dev libbrotli-dev libsnappy-dev libzopfli-dev libgif-dev libtiff-dev

# Not sure why it can't find these headers. Copy them where they can be found.
RUN cp /usr/include/openjpeg-2.3/*.h /usr/include/
RUN python3.7 -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"
RUN pip3 install wheel
# Dependencies for our Django app.
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM nvidia/cuda:10.0-cudnn7-runtime AS build-image
COPY --from=compile-image /openpose /openpose
COPY --from=compile-image /opt/venv /opt/venv
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
python3.7-dev python3-pip git g++ wget make libopencv-dev \
libgoogle-glog-dev libboost-all-dev libcaffe-cuda-dev libhdf5-dev libatlas-base-dev

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

# Download weights file required for object detection
WORKDIR /usr/src/app/moedx/pytorch_objectdetecttrack/config
RUN wget http://opencv.facetraining.mobiledgex.net/files/yolov3.weights
WORKDIR /usr/src/app/moedx
COPY . /usr/src/app
# Initialize the database.
RUN python manage.py makemigrations tracker
RUN python manage.py migrate
# port for REST
EXPOSE 8008/tcp
# port for persistent TCP server
EXPOSE 8011/tcp

# Fix for "click" Python library, a uvicorn dependency.
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD ["uvicorn","moedx.asgi:application","--host", "0.0.0.0","--port","8008","--workers","2"]
