use_frameworks!

platform :ios, '11.4'

# Default Specs.git:
source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-art', :sources => ['cocoapods-releases'] 

target 'ARShooter' do
  pod 'IOSMatchingEngine'
  pod 'Socket.IO-Client-Swift', '~> 15.1.0'

  target 'ARShooterTests' do
    inherit! :search_paths  
  end
  
  target 'ARShooterUITests' do
    inherit! :search_paths
  end
end
