use_frameworks!

platform :ios, '11.4'

# Default Specs.git:
source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-art', :sources => ['cocoapods-releases'] 

target 'ARShooterSkeleton' do
  pod 'MobiledgeXiOSLibrary'

  target 'ARShooterSkeletonTests' do
    inherit! :search_paths  
  end
  
  target 'ARShooterSkeletonUITests' do
    inherit! :search_paths
  end
end
